### ISSUE TITLE
SFOS-Chum repo names changed format

### ISSUE THREAD

**Issue by Olf0** [sailfishos-chum/sailfishos-chum.github.io#30]
The format of the repository names at [SailfishOS:Chum](https://build.sailfishos.org/project/show/sailfishos:chum) were changed from `a.b.c.x_arch` to `a.b_arch`.  The specific switch occurred from `4.5.0.25_{aarch64|armv7hl|i486}` to `4.6_{aarch64|armv7hl|i486}`.

By looking at [`chumweb/repo_loader.py`](https://github.com/sailfishos-chum/sailfishos-chum.github.io/blob/master/chumweb/repo_loader.py) I do not (yet) see the culprit, IMO the function [`cmp_repo_version`](https://github.com/sailfishos-chum/sailfishos-chum.github.io/blob/master/chumweb/repo_loader.py#L63-L84) (rsp. the function [`filter_newest_repos`](https://github.com/sailfishos-chum/sailfishos-chum.github.io/blob/master/chumweb/repo_loader.py#L54) it is embedded into) should still work as intended by using `zip`.

But obviously something fails to cope with this format change, because [`repo_version`](https://github.com/sailfishos-chum/sailfishos-chum.github.io/blob/master/chumweb/www/views/layouts/base.html#L48) still resolves to `4.5.0.25` via [`repo_info.version`](https://github.com/sailfishos-chum/sailfishos-chum.github.io/blob/master/chumweb/static_site_gen.py#L119), as seen by the generated result at the bottom of the left column on [sailfishos-chum.github.io](https://sailfishos-chum.github.io/).

**Comment by Olf0** [comment]
Ah, the repos to evaluate are hardcoded in the [CI/CD-configuration file](https://github.com/sailfishos-chum/sailfishos-chum.github.io/blob/master/.github/workflows/gen-site.yaml#L30).

Mmmh, what is all the evaluation logic in Python good for, when the newest repos are statically set for building the [sailfishos-chum.github.io](https://sailfishos-chum.github.io/) website?  Well, just wondering, I do not *need* an answer in depth, while it would allow me to comprehend the answer to the real question: Is it sufficient to alter the [values in the CI/CD-config](https://github.com/sailfishos-chum/sailfishos-chum.github.io/blob/master/.github/workflows/gen-site.yaml#L30) and rebuild?

**Comment by HenkKalkwater** [comment]
Editing the .ci-file should be enough. There is logic to automatically fetch the repositories for the latest SFOS version from OBS, but it is not used in production (there is an open issue for that, I may link ot later)

Op Woensdag 17 juli 2024 schreef olf:

**Comment by Olf0** [comment]
Seems to have worked fine. :smile:
